Get-AppxPackage -Name *WindowsMaps* | Remove-AppxPackage ;
Get-AppxPackage -Name *WindowsAlarms* | Remove-AppxPackage ;
Get-AppxPackage *windowscommunicationsapps* | Remove-AppxPackage ;
Get-AppxPackage -Name *WindowsPhone* | Remove-AppxPackage ;
Get-AppxPackage -Name *BingNews* | Remove-AppxPackage ;
Get-AppxPackage -Name *BingFinance* | Remove-AppxPackage ;
Get-AppxPackage -Name *BingSports* | Remove-AppxPackage ;
Get-AppxPackage -Name *BingWeather* | Remove-AppxPackage ;
Get-AppxPackage -Name *ZuneVideo* | Remove-AppxPackage ;
Get-AppxPackage -Name *ZuneMusic* | Remove-AppxPackage ;
Get-AppxPackage -Name *MicrosoftOfficeHub* | Remove-AppxPackage ;
Get-AppxPackage -Name *Messaging* | Remove-AppxPackage ;
Get-AppxPackage -Name *Advertising.Xaml* | Remove-AppxPackage ;
Get-AppxPackage -Name *Office.OneNote* | Remove-AppxPackage ;
Get-AppxPackage -Name *OneConnect* | Remove-AppxPackage ;
Get-AppxPackage -Name *Phone* | Remove-AppxPackage ;
Get-AppxPackage -Name *Sway* | Remove-AppxPackage ;
Get-AppxPackage -Name *3DBuilder* | Remove-AppxPackage ;
Get-AppxPackage -Name *Wallet* | Remove-AppxPackage ;
Get-AppxPackage -Name *BubbleWitch* | Remove-AppxPackage ;
Get-AppxPackage -Name *HiddenCity* | Remove-AppxPackage ;
Get-AppxPackage -Name *Disney* | Remove-AppxPackage ;
Get-AppxPackage -Name *MarchofEmpires* | Remove-AppxPackage ;
Get-AppxPackage -Name *CandyCrush* | Remove-AppxPackage ;
Get-AppxPackage -Name *MicrosoftSolitaireCollection* | Remove-AppxPackage ;
Get-AppxPackage -Name *RoyalRev* | Remove-AppxPackage ;
Get-AppxPackage -Name *PowerBI* | Remove-AppxPackage ;
Get-AppxPackage -Name *Eclipse* | Remove-AppxPackage ;
Get-AppxPackage -Name *AdobePhotoshopExpress* | Remove-AppxPackage ;
Get-AppxPackage -Name *Sling* | Remove-AppxPackage ;
Get-AppxPackage -Name *Duolingo* | Remove-AppxPackage ;
Get-AppxPackage -Name *PhototasticCollage* | Remove-AppxPackage ;
Get-AppxPackage -Name *Keeper* | Remove-AppxPackage ;
Get-AppxPackage -Name *SketchBook* | Remove-AppxPackage ;
Get-AppxPackage -Name *DolbyAccess* | Remove-AppxPackage ;
Get-AppxPackage -Name *twitter* | Remove-AppxPackage ;
Get-AppxPackage -Name *Facebook* | Remove-AppxPackage ;
Get-AppxPackage *AdobeSystemsIncorporated.AdobePhotoshopExpress* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.Asphalt8Airborne* | Remove-AppxPackage ;
Get-AppxPackage *microsoft.windowscommunicationsapps* | Remove-AppxPackage ;
Get-AppxPackage *king.com.CandyCrushSodaSaga* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.DrawboardPDF* | Remove-AppxPackage ;
Get-AppxPackage *Facebook* | Remove-AppxPackage ;
Get-AppxPackage *BethesdaSoftworks.FalloutShelter* | Remove-AppxPackage ;
Get-AppxPackage *FarmVille2CountryEscape* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.ZuneMusic* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.WindowsMaps* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.Messaging* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.Wallet* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage ;
Get-AppxPackage *Todos* | Remove-AppxPackage ;
Get-AppxPackage *ConnectivityStore* | Remove-AppxPackage ;
Get-AppxPackage *MinecraftUWP* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.OneConnect* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.BingFinance* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.ZuneVideo* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.BingNews* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage ;
Get-AppxPackage *OneNote* | Remove-AppxPackage ;
Get-AppxPackage *PandoraMediaInc* | Remove-AppxPackage ;
Get-AppxPackage *CommsPhone* | Remove-AppxPackage ;
Get-AppxPackage *windowsphone* | Remove-AppxPackage ;
Get-AppxPackage *flaregamesGmbH.RoyalRevolt2* | Remove-AppxPackage ;
Get-AppxPackage *AutodeskSketchBook* | Remove-AppxPackage ;
Get-AppxPackage *bingsports* | Remove-AppxPackage ;
Get-AppxPackage *Office.Sway* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.Getstarted* | Remove-AppxPackage ;
Get-AppxPackage *Twitter* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft3DViewer* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.BingWeather* | Remove-AppxPackage ;
Get-AppxPackage *XboxOneSmartGlass* | Remove-AppxPackage ;
Get-AppxPackage *Microsoft.XboxSpeechToTextOverlay* | Remove-AppxPackage ;
# C:\Windows\SysWOW64\OneDriveSetup.exe /uninstall ;