#!/bin/bash
args=""
for a in "$@"
do
  if [[ "$args" != "" ]]
  then
    args+="%20"
  fi
  args+=$a
done

google-chrome-stable "https://wiki.archlinux.org/index.php?title=Special%3ASearch&profile=default&search=$args&fulltext=Search"
