#!/bin/bash

function download {
  mkdir -p ~/Music/$1/vid
  cd ~/Music/$1/vid
  youtube-dl -x --audio-format mp3 --audio-quality 0 ytuser:$1 --playlist-start $2 -o "%(title)s.%(ext)s"
  mv ~/Music/$1/vid/*.mp3 ~/Music/$1/
}


if [[ "$1" == "all" ]]; then
  download electropose1 1
  download Liquicity 1
  download MrRevillz 1
  download MrSuicideSheep 1
  download NoCopyrightSounds 1
else
  download $1 $2
fi
