#!/bin/bash

icon="$HOME/.icons/lock.png"
tmpbg='/tmp/screen.png'

(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -geometry +896+476 -composite -matte "$tmpbg"
convert "$tmpbg" "$icon" -geometry +2543+320 -composite -matte "$tmpbg"
i3lock -i "$tmpbg" -u
