#!/bin/bash

function play {
  basename `pwd` | figlet | lolcat
  mpv *.mp3 --shuffle
}


cd ~/Music
arg=${1,,}
if [[ "$arg" == "suicidesheep" ]]; then
   cd MrSuicideSheep
elif [[ "$arg" == "ss" ]]; then
  cd MrSuicideSheep
elif [[ "$arg" == "electropose" ]]; then
  cd electropose1
elif [[ "$arg" == "ncs" ]]; then
  cd NoCopyrightSounds
elif [[ "$arg" == "proximity" ]]; then
  cd PandoraMus1c
elif [[ "$arg" == "liquicity" ]]; then
  cd Liquicity
elif [[ "$arg" == "monstercat" ]]; then
  cd MonstercatMedia
elif [[ "$arg" == "mrrevillz" ]]; then
  cd MrRevillz
else
  echo "ss - SuicideSheep"
  echo "electropose - Electropose"
  echo "ncs - NoCopyrightSounds"
  echo "proximity - Proximity"
  echo "liquicity - Liquicity"
  echo "monstercat - Monstercat"
  echo "mrrevillz - MrRevillz"
  exit
fi

play

