#!/bin/bash

#Thank you unsplash and unsplash.it!
#Script based on Tymscar's Unsplash script. http://www.github.com/tymscar

# Downloading picture

function download {
  curl https://unsplash.it/1920/1080/?random > ~/Pictures/Wall/$1.jpg
}

#check args
if [[ "$1" == "lvds" ]]; then
  download lvds
elif [[ "$1" == "vga" ]]; then
  download vga
else
  download lvds
  download vga
fi

# Setting wallpaper
nitrogen --restore
