---
# Setup default Windows settings the way I like

- name: Set an environment variable for the repos folder
  ansible.windows.win_environment:
    name: REPOS
    value: C:\Users\{{ ansible_user }}\repos
    state: present
    level: user

- name: Set Dark mode (apps)
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: AppsUseLightTheme
    data: 0
    type: dword
    state: present

- name: Set Dark mode (system)
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: SystemUsesLightTheme
    data: 0
    type: dword
    state: present

- name: Show hidden files in Explorer
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1
    type: dword
    state: present

- name: Show System files in Explorer
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSuperHidden
    data: 1
    type: dword
    state: present

- name: Show file extensions in Explorer
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword
    state: present

- name: Open This PC in Explorer by default
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword
    state: present

- name: Show path in title bar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState
    name: FullPath
    data: 1
    type: dword
    state: present


# https://learn.microsoft.com/en-us/windows/deployment/update/waas-restart
- name: Disable automatic restart after updates outside of active hours
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: SetActiveHours
    data: 0
    type: dword
    state: present

# https://www.tenforums.com/tutorials/107865-add-remove-lid-close-action-power-options-windows.html
- name: Set laptop lid close to do nothing
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\4f971e89-eebd-4455-a8de-9e59040e7347\5ca83367-6e45-459f-a27b-476b1d01c936
    name: Attributes
    data: 0
    type: dword
    state: present

# https://www.makeuseof.com/ways-to-hide-desktop-icons-on-windows/
- name: Hide Desktop Icons
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoDesktop
    data: 1
    type: dword
    state: present

- name: Apply Windows updates
  ansible.windows.win_updates:
    category_names:  '*'
    reboot: no