
---
# Install web dev applications

- name: Install all the Chromes (winget)
  ansible.windows.win_powershell:
    script: |
      winget install Google.Chrome.Dev
      winget install Google.Chrome.Beta
      winget install Google.Chrome.Canary

- name: Install all the Firefoxes (winget)
  ansible.windows.win_powershell:
    script: |
      winget install Mozilla.Firefox.Beta
      winget install Mozilla.Firefox.DeveloperEdition

- name: Install all the Edges (winget)
  ansible.windows.win_powershell:
    script: |
      winget install Microsoft.Edge.Dev
      winget install Microsoft.Edge.Beta