# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  showRootItemInFileTree: false
  nerdFontsVersion: "3"
  splitDiff: "always"
  skipRewordInEditorWarning: true
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
disableStartupPopups: true
keybinding:
  commits:
    moveDownCommit: "<c-d>" # move commit down one - Changed from <c-j> to <c-d> to avoid conflict with vscode focus group
    moveUpCommit: "<c-u>" # move commit up one - Changed from <c-k> to <c-u> to avoid conflict with vscode focus group

refresher:
  fetchInterval: 3600