#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias wfica='/opt/Citrix/ICAClient/wfica'
PS1='[\u@\h \W]\$ '

export EDITOR=nano
export PATH=$PATH:~/.scripts
neofetch
