#!/bin/bash

icon="$HOME/.icons/lock.png"
tmpbg='/tmp/screen.png'

(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg"
convert "$tmpbg" "$icon" -gravity NorthWest -geometry +860+400 -composite -matte "$tmpbg"
convert "$tmpbg" "$icon" -gravity NorthEast -geometry +550+250 -composite -matte "$tmpbg"
i3lock -i "$tmpbg" -u
