#!/bin/bash
args=""
for a in "$@"
do
  if [[ "$args" != "" ]]
  then
    args+="%20"
  fi
  args+=$a
done

google-chrome-stable https://www.youtube.com/results?search_query=$args&page=&utm_source=opensearch
