#!/bin/bash
rsync -avhu --delete --progress ~/Documents/ /run/media/brizzz/4C0922C30FCFAB0B/Documents/
rsync -avhu --delete --progress ~/HDD/AKSH/ /run/media/brizzz/4C0922C30FCFAB0B/AKSH/
rsync -avhu --delete --progress ~/HDD/Games/ /run/media/brizzz/4C0922C30FCFAB0B/Games/
rsync -avhu --delete --progress ~/HDD/Lectures/ /run/media/brizzz/4C0922C30FCFAB0B/Lectures/
rsync -avhu --delete --progress ~/HDD/Music/ /run/media/brizzz/4C0922C30FCFAB0B/Music/
rsync -avhu --delete --progress ~/HDD/OS/ /run/media/brizzz/4C0922C30FCFAB0B/OS/
rsync -avhu --delete --progress ~/HDD/Photos\ 2015/ /run/media/brizzz/4C0922C30FCFAB0B/Photos\ 2015/
rsync -avhu --delete --progress ~/HDD/Pictures/ /run/media/brizzz/4C0922C30FCFAB0B/Pictures/
rsync -avhu --delete --progress ~/HDD/Software/ /run/media/brizzz/4C0922C30FCFAB0B/Software/
rsync -avhu --delete --progress ~/HDD/Videos/ /run/media/brizzz/4C0922C30FCFAB0B/Videos/
#reverse
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Documents/ ~/Documents/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/AKSH/ ~/HDD/AKSH/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Games/ ~/HDD/Games/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Lectures/ ~/HDD/Lectures/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Music/ ~/HDD/Music/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/OS/ ~/HDD/OS/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Photos\ 2015/ ~/HDD/Photos\ 2015/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Pictures/ ~/HDD/Pictures/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Software/ ~/HDD/Software/
rsync -rtuv --progress /run/media/brizzz/4C0922C30FCFAB0B/Videos/ ~/HDD/Videos/
