#!/bin/bash
CAPACITY=`cat /sys/class/power_supply/BAT0/capacity`
STATUS=`cat /sys/class/power_supply/BAT0/status`
if [ "$STATUS" == "Charging" ]; then
  ICON=""
elif [ $CAPACITY -le 15 ]; then
  ICON=""
elif [ $CAPACITY -le 40 ]; then
  ICON=""
elif [ $CAPACITY -le 65 ]; then
  ICON=""
elif [ $CAPACITY -le 85 ]; then
  ICON=""
else
  ICON=""
fi
echo -n "$ICON $CAPACITY%"
