#!/bin/bash

icon="$HOME/.icons/lock.png"
tmpbg='/tmp/screen.png'

(( $# )) && { icon=$1; }

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
composite -gravity center "$icon" "$tmpbg" "$tmpbg"
i3lock -i "$tmpbg" -u
