#!/bin/bash

# Thank you unsplash and unsplash.it!
# Script based on Tymscar's Unsplash script. http://www.github.com/tymscar
# Inspired by https://github.com/mfin/earth-view-wallpaper for Earth View

# Downloading picture

NEWFILE='/home/brizzz/Pictures/Wall/lvds.new.jpg'
FILE='/home/brizzz/Pictures/Wall/lvds.jpg'

function download {
  CHANCE=$((RANDOM % 3))
  if [[ $CHANCE == 0 ]]; then
	  echo "Earth View"
	  curl `shuf -n 1 ~/Pictures/Wall/earth_view.txt` > $NEWFILE
	  if [ $? -ne 0 ]; then
		  rm $NEWFILE
          fi
  else
	  echo "Unsplash"
	  curl https://unsplash.it/1920/1080/?random > $NEWFILE
	  if [ $? -ne 0 ]; then
		  rm $NEWFILE
          fi
  fi
  if [ -e $NEWFILE ]; then
    cp $NEWFILE $FILE
    nitrogen --restore
  fi
}

# Restore Previous wallpaper
nitrogen --restore

# Check args
download 

