#!/usr/bin/perl

# File generated by menutray v0.45

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/brizzz/.config/menutray/schema.pl' instead!

use utf8;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('archlinux');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "thunar &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $item->signal_connect('activate', sub {system "i3\-sensible\-terminal &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "chrome &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Instant\ messaging");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-users",q{menu}));
    $item->signal_connect('activate', sub {system "pidgin &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Accessories");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("About\ Xfce");
    $app->signal_connect('activate', sub {system "xfce4\-about &"});
    $app->set_property('tooltip_text', "Information\ about\ the\ Xfce\ Desktop\ Environment");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-about",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Application\ Finder");
    $app->signal_connect('activate', sub {system "xfce4\-appfinder &"});
    $app->set_property('tooltip_text', "Find\ and\ launch\ applications\ installed\ on\ your\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("edit\-find",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/atom &"});
    $app->set_property('tooltip_text', "Chrome\-based\ text\ editor\ from\ Github");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Calculator");
    $app->signal_connect('activate', sub {system "gnome\-calculator &"});
    $app->set_property('tooltip_text', "Perform\ arithmetic\,\ scientific\ or\ financial\ calculations");
    $app->set_image('Gtk2::Image'->new_from_icon_name("accessories\-calculator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Clipman");
    $app->signal_connect('activate', sub {system "xfce4\-clipman &"});
    $app->set_property('tooltip_text', "Clipboard\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-clipman\-plugin",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ FileManager &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Galculator");
    $app->signal_connect('activate', sub {system "galculator &"});
    $app->set_property('tooltip_text', "Perform\ simple\ and\ scientific\ calculations");
    $app->set_image('Gtk2::Image'->new_from_icon_name("galculator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Leafpad");
    $app->signal_connect('activate', sub {system "leafpad &"});
    $app->set_property('tooltip_text', "Simple\ text\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("leafpad",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mousepad");
    $app->signal_connect('activate', sub {system "mousepad &"});
    $app->set_property('tooltip_text', "Simple\ Text\ Editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("accessories\-text\-editor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Notes");
    $app->signal_connect('activate', sub {system "xfce4\-notes &"});
    $app->set_property('tooltip_text', "Ideal\ for\ your\ quick\ notes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-notes\-plugin",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Orage\ Globaltime");
    $app->signal_connect('activate', sub {system "globaltime &"});
    $app->set_property('tooltip_text', "Show\ clocks\ from\ different\ countries");
    $app->set_image('Gtk2::Image'->new_from_icon_name("orage_globaltime",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Root\ Terminal");
    $app->signal_connect('activate', sub {system "gksu\ \-l\ gnome\-terminal &"});
    $app->set_property('tooltip_text', "Opens\ a\ terminal\ as\ the\ root\ user\,\ using\ gksu\ to\ ask\ for\ the\ password");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gksu\-root\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Run\ Program\.\.\.");
    $app->signal_connect('activate', sub {system "xfce4\-appfinder\ \-\-collapsed &"});
    $app->set_property('tooltip_text', "Run\ a\ program");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Screenshot");
    $app->signal_connect('activate', sub {system "xfce4\-screenshooter &"});
    $app->set_property('tooltip_text', "Take\ screenshots\ of\ the\ entire\ screen\,\ of\ the\ active\ window\ or\ of\ a\ region");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applets\-screenshooter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sensor\ Viewer");
    $app->signal_connect('activate', sub {system "xfce4\-sensors &"});
    $app->set_property('tooltip_text', "Show\ sensor\ values\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce\-sensors",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Shutter");
    $app->signal_connect('activate', sub {system "shutter &"});
    $app->set_property('tooltip_text', "Capture\,\ edit\ and\ share\ screenshots");
    $app->set_image('Gtk2::Image'->new_from_icon_name("shutter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sublime\ Text");
    $app->signal_connect('activate', sub {system "subl &"});
    $app->set_property('tooltip_text', "Sophisticated\ text\ editor\ for\ code\,\ html\ and\ prose");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sublime\-text",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Task\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-taskmanager &"});
    $app->set_property('tooltip_text', "Easy\ to\ use\ task\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminal\ Emulator");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ TerminalEmulator &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xarchiver");
    $app->signal_connect('activate', sub {system "xarchiver &"});
    $app->set_property('tooltip_text', "A\ GTK\+\ only\ archive\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xarchiver",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfburn");
    $app->signal_connect('activate', sub {system "xfburn &"});
    $app->set_property('tooltip_text', "CD\ and\ DVD\ burning\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("media\-cdrom",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Development");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Android\ SDK");
    $app->signal_connect('activate', sub {system "android &"});
    $app->set_property('tooltip_text', "Android\ Software\ Development\ Kit");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-sdk",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Android\ Studio");
    $app->signal_connect('activate', sub {system "android\-studio &"});
    $app->set_property('tooltip_text', "Develop\ with\ pleasure\!");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-studio",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/atom &"});
    $app->set_property('tooltip_text', "Chrome\-based\ text\ editor\ from\ Github");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Brackets");
    $app->signal_connect('activate', sub {system "\/opt\/brackets\/brackets &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("brackets",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Mission\ Control");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jmc &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Monitoring\ and\ Management\ Console");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jconsole &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ VisualVM");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/bin\/jvisualvm &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Education");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Games");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("PlayOnLinux");
    $app->signal_connect('activate', sub {system "playonlinux &"});
    $app->set_property('tooltip_text', "PlayOnLinux");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/playonlinux\/etc\/playonlinux\.png",16,16)));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Graphics");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Agave");
    $app->signal_connect('activate', sub {system "agave &"});
    $app->set_property('tooltip_text', "Generate\ color\ schemes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("agave",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Gpick");
    $app->signal_connect('activate', sub {system "gpick &"});
    $app->set_property('tooltip_text', "Color\ picker");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gpick",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Ristretto\ Image\ Viewer");
    $app->signal_connect('activate', sub {system "ristretto &"});
    $app->set_property('tooltip_text', "Look\ at\ your\ images\ easily");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ristretto",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Audacity");
    $app->signal_connect('activate', sub {system "env\ UBUNTU_MENUPROXY\=0\ audacity &"});
    $app->set_property('tooltip_text', "Record\ and\ edit\ audio\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("audacity",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Audio\ Mixer");
    $app->signal_connect('activate', sub {system "xfce4\-mixer &"});
    $app->set_property('tooltip_text', "Adjust\ volume\ levels");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HandBrake");
    $app->signal_connect('activate', sub {system "ghb &"});
    $app->set_property('tooltip_text', "Transcodes\ DVD\,\ Bluray\,\ and\ other\ media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("hb\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-profile\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mpv",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Spotify");
    $app->signal_connect('activate', sub {system "spotify &"});
    $app->set_property('tooltip_text', "Spotify\ streaming\ music\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spotify\-client",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("traGtor");
    $app->signal_connect('activate', sub {system "tragtor &"});
    $app->set_property('tooltip_text', "traGtor\ \-\ a\ GUI\ for\ FFmpeg\ for\ audio\ and\ video\-conversion");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/tragtor\.svg",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfburn");
    $app->signal_connect('activate', sub {system "xfburn &"});
    $app->set_property('tooltip_text', "CD\ and\ DVD\ burning\ application");
    $app->set_image('Gtk2::Image'->new_from_icon_name("media\-cdrom",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Network");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Citrix\ Connection\ Centre");
    $app->signal_connect('activate', sub {system "\/opt\/Citrix\/ICAClient\/util\/conncenter\ \-\-icaroot\ \/opt\/Citrix\/ICAClient &"});
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/opt\/Citrix\/ICAClient\/icons\/manager\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Citrix\ Receiver\ Preferences");
    $app->signal_connect('activate', sub {system "\/opt\/Citrix\/ICAClient\/util\/configmgr\ \-\-icaroot\ \/opt\/Citrix\/ICAClient &"});
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/opt\/Citrix\/ICAClient\/icons\/manager\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Citrix\ Receiver\ Self\ Service");
    $app->signal_connect('activate', sub {system "\/opt\/Citrix\/ICAClient\/selfservice\ \-\-icaroot\ \/opt\/Citrix\/ICAClient &"});
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/opt\/Citrix\/ICAClient\/icons\/manager\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firefox");
    $app->signal_connect('activate', sub {system "firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firefox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Google\ Chrome");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/google\-chrome\-stable &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("google\-chrome",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mail\ Reader");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ MailReader &"});
    $app->set_property('tooltip_text', "Read\ your\ email");
    $app->set_image('Gtk2::Image'->new_from_icon_name("internet\-mail",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SftpMan");
    $app->signal_connect('activate', sub {system "sftpman\-gtk &"});
    $app->set_property('tooltip_text', "Mount\ SSHFS\/SFTP\ filesystems");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sftpman\-gtk",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("TeamViewer\ 11");
    $app->signal_connect('activate', sub {system "\/opt\/teamviewer\/tv_bin\/script\/teamviewer &"});
    $app->set_property('tooltip_text', "TeamViewer\ Remote\ Control\ Application");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/opt\/teamviewer\/tv_bin\/desktop\/teamviewer\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("transmission",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ WebBrowser &"});
    $app->set_property('tooltip_text', "Browse\ the\ web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Office");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Dictionary");
    $app->signal_connect('activate', sub {system "xfce4\-dict &"});
    $app->set_property('tooltip_text', "A\ client\ program\ to\ query\ different\ dictionaries\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-dict",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ePDFViewer");
    $app->signal_connect('activate', sub {system "epdfview &"});
    $app->set_property('tooltip_text', "Lightweight\ PDF\ document\ viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("epdfview",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\ by\ using\ Base\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Orage\ Calendar");
    $app->signal_connect('activate', sub {system "orage &"});
    $app->set_property('tooltip_text', "Desktop\ calendar");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfcalendar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Orage\ Globaltime");
    $app->signal_connect('activate', sub {system "globaltime &"});
    $app->set_property('tooltip_text', "Show\ clocks\ from\ different\ countries");
    $app->set_image('Gtk2::Image'->new_from_icon_name("orage_globaltime",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Settings");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Accessibility");
    $app->signal_connect('activate', sub {system "xfce4\-accessibility\-settings &"});
    $app->set_property('tooltip_text', "Improve\ keyboard\ and\ mouse\ accessibility");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-accessibility",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Appearance");
    $app->signal_connect('activate', sub {system "xfce4\-appearance\-settings &"});
    $app->set_property('tooltip_text', "Customize\ the\ look\ of\ your\ desktop");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bluetooth\ Adapters");
    $app->signal_connect('activate', sub {system "blueman\-adapters &"});
    $app->set_property('tooltip_text', "Set\ Bluetooth\ Adapter\ Properties");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blueman\-device",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bluetooth\ Manager");
    $app->signal_connect('activate', sub {system "blueman\-manager &"});
    $app->set_property('tooltip_text', "Blueman\ Bluetooth\ Manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blueman",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Connman\ Settings");
    $app->signal_connect('activate', sub {system "connman\-gtk &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Customize\ Look\ and\ Feel");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Desktop");
    $app->signal_connect('activate', sub {system "xfdesktop\-settings &"});
    $app->set_property('tooltip_text', "Set\ desktop\ background\ and\ menu\ and\ icon\ behavior");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-wallpaper",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Display");
    $app->signal_connect('activate', sub {system "xfce4\-display\-settings &"});
    $app->set_property('tooltip_text', "Configure\ screen\ settings\ and\ layout");
    $app->set_image('Gtk2::Image'->new_from_icon_name("video\-display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "thunar\-settings &"});
    $app->set_property('tooltip_text', "Configure\ the\ Thunar\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/jre\/bin\/jcontrol &"});
    $app->set_property('tooltip_text', "Java\ Control\ Panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-jcontrol\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Java\ Policy\ Settings");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-8\-jdk\/jre\/bin\/policytool &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("sun\-java\-jdk8",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Keyboard");
    $app->signal_connect('activate', sub {system "xfce4\-keyboard\-settings &"});
    $app->set_property('tooltip_text', "Edit\ keyboard\ settings\ and\ application\ shortcuts");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-keyboard",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MIME\ Type\ Editor");
    $app->signal_connect('activate', sub {system "xfce4\-mime\-settings &"});
    $app->set_property('tooltip_text', "Associate\ applications\ with\ MIME\ types");
    $app->set_image('Gtk2::Image'->new_from_icon_name("application\-x\-executable",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Monitor\ Settings");
    $app->signal_connect('activate', sub {system "lxrandr &"});
    $app->set_property('tooltip_text', "Change\ screen\ resolution\ and\ configure\ external\ monitors");
    $app->set_image('Gtk2::Image'->new_from_icon_name("video\-display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mouse\ and\ Touchpad");
    $app->signal_connect('activate', sub {system "xfce4\-mouse\-settings &"});
    $app->set_property('tooltip_text', "Configure\ pointer\ device\ behavior\ and\ appearance");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-peripherals",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Notifications");
    $app->signal_connect('activate', sub {system "xfce4\-notifyd\-config &"});
    $app->set_property('tooltip_text', "Customize\ how\ notifications\ appear\ on\ your\ screen");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-notifyd",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Orage\ preferences");
    $app->signal_connect('activate', sub {system "orage\ \-p &"});
    $app->set_property('tooltip_text', "Settings\ for\ the\ Xfce\ 4\ Calendar\ Application\ \(Orage\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfcalendar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Panel");
    $app->signal_connect('activate', sub {system "xfce4\-panel\ \-\-preferences &"});
    $app->set_property('tooltip_text', "Customize\ the\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-panel",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Power\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-power\-manager\-settings &"});
    $app->set_property('tooltip_text', "Settings\ for\ the\ Xfce\ Power\ Manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-power\-manager\-settings",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app->signal_connect('activate', sub {system "exo\-preferred\-applications &"});
    $app->set_property('tooltip_text', "Preferred\ Applications\ \(Web\ Browser\,\ Mail\ Reader\ and\ Terminal\ Emulator\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-default\-applications",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Privilege\ granting");
    $app->signal_connect('activate', sub {system "gksu\-properties &"});
    $app->set_property('tooltip_text', "Configure\ behavior\ of\ the\ privilege\-granting\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gksu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Removable\ Drives\ and\ Media");
    $app->signal_connect('activate', sub {system "thunar\-volman\-settings &"});
    $app->set_property('tooltip_text', "Configure\ management\ of\ removable\ drives\ and\ media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drive\-removable\-media",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Session\ and\ Startup");
    $app->signal_connect('activate', sub {system "xfce4\-session\-settings &"});
    $app->set_property('tooltip_text', "Customize\ desktop\ startup\ and\ splash\ screen");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-session",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Settings\ Editor");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-editor &"});
    $app->set_property('tooltip_text', "Graphical\ settings\ editor\ for\ Xfconf");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Settings\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-manager &"});
    $app->set_property('tooltip_text', "Graphical\ Settings\ Manager\ for\ Xfce\ 4");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("systemadm");
    $app->signal_connect('activate', sub {system "systemadm &"});
    $app->set_property('tooltip_text', "Manage\ Systemd\ Units");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Window\ Manager");
    $app->signal_connect('activate', sub {system "xfwm4\-settings &"});
    $app->set_property('tooltip_text', "Configure\ window\ behavior\ and\ shortcuts");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfwm4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Window\ Manager\ Tweaks");
    $app->signal_connect('activate', sub {system "xfwm4\-tweaks\-settings &"});
    $app->set_property('tooltip_text', "Fine\-tune\ window\ behaviour\ and\ effects");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wmtweaks",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Workspaces");
    $app->signal_connect('activate', sub {system "xfwm4\-workspace\-settings &"});
    $app->set_property('tooltip_text', "Configure\ layout\,\ names\ and\ margins");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-workspaces",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("System");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted_polkit &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gparted",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Grsync");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/grsync\ \-i &"});
    $app->set_property('tooltip_text', "Synchronize\ files\ and\ folders\ \(a\ GTK\ GUI\ for\ rsync\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("grsync",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Log\ Out");
    $app->signal_connect('activate', sub {system "xfce4\-session\-logout &"});
    $app->set_property('tooltip_text', "Log\ out\ of\ the\ Xfce\ Desktop");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-log\-out",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sensor\ Viewer");
    $app->signal_connect('activate', sub {system "xfce4\-sensors &"});
    $app->set_property('tooltip_text', "Show\ sensor\ values\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce\-sensors",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("systemadm");
    $app->signal_connect('activate', sub {system "systemadm &"});
    $app->set_property('tooltip_text', "Manage\ Systemd\ Units");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Task\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-taskmanager &"});
    $app->set_property('tooltip_text', "Easy\ to\ use\ task\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Termite");
    $app->signal_connect('activate', sub {system "termite &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("UXTerm");
    $app->signal_connect('activate', sub {system "uxterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("WinUSB");
    $app->signal_connect('activate', sub {system "winusbgui &"});
    $app->set_property('tooltip_text', "Create\ Windows\ USB\ stick\ installer\ from\ a\ real\ Windows\ DVD\ or\ an\ image\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("winusbgui\-icon",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Xfce\ Terminal");
    $app->signal_connect('activate', sub {system "xfce4\-terminal &"});
    $app->set_property('tooltip_text', "Terminal\ Emulator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("XTerm");
    $app->signal_connect('activate', sub {system "xterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Menutray");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Config");
    $app->signal_connect('activate', sub {system "atom\ \/home\/brizzz\/\.config\/menutray\/config\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Menu");
    $app->signal_connect('activate', sub {system "atom\ \/home\/brizzz\/\.config\/menutray\/menu\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Schema");
    $app->signal_connect('activate', sub {system "atom\ \/home\/brizzz\/\.config\/menutray\/schema\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
