---
# Install dev applications

- name: Install WinMerge
  win_chocolatey:
    name: winmerge
    state: present

- name: Install WinSCP
  win_chocolatey:
    name: winscp
    state: present

- name: Install gsudo
  win_chocolatey:
    name: gsudo
    state: present

- name: Install Alacritty
  win_chocolatey:
    name: alacritty
    state: present

- name: Junction Alacritty settings
  ansible.windows.win_powershell:
    script: |
      $source = "$env:AppData\alacritty"
      $target  = "{{ dotfiles_repo_fullpath }}\common\config\alacritty"
      $type = "Junction"
      $existing = Get-Item -Path $source -ErrorAction SilentlyContinue
      if ($?) {
        if ($existing.LinkType -eq $type)
        {
          $Ansible.Changed = $false
          exit
        }
        Remove-Item -Path $source
      }
      New-Item -ItemType Junction -Path "$source" -Target "$target"

- name: Remove linux import from Alacritty
  community.windows.win_lineinfile:
    regex: 'linux\.yml'
    backrefs: yes
    path: "%AppData%\\alacritty\\alacritty.yml"
    state: absent

- name: Install Insomnia
  win_chocolatey:
    name: insomnia-rest-api-client
    state: present

- name: Install Python3
  win_chocolatey:
    name: python3
    state: present

- name: Remove dummy python exe
  ansible.windows.win_powershell:
    script: |
      $source = "$env:LocalAppData\Microsoft\WindowsApps"
      Remove-Item -Path "$source\python.exe" -Force
      Remove-Item -Path "$source\python3.exe" -Force

- name: Install NodeJS
  win_chocolatey:
    name: nodejs.install
    state: present

- name: Install ripgrep
  win_chocolatey:
    name: ripgrep
    state: present

- name: Install fzf
  win_chocolatey:
    name: fzf
    state: present

- name: Install zoxide
  win_chocolatey:
    name: zoxide
    state: present

- name: Install bat
  win_chocolatey:
    name: bat
    state: present

- name: Install jq
  win_chocolatey:
    name: jq
    state: present

- name: Install yq
  win_chocolatey:
    name: yq
    state: present

- name: Install lazygit
  win_chocolatey:
    name: lazygit
    state: present

- name: Configure lazygit
  ansible.windows.win_powershell:
    script: |
      $source = "$env:AppData\lazygit\config.yml"
      $target = "{{ dotfiles_repo_fullpath }}\common\config\lazygit\config.yml"
      $type = "HardLink"
      $existing = Get-Item -Path $source -ErrorAction SilentlyContinue
      if ($?) {
        if ($existing.LinkType -eq $type)
        {
          $Ansible.Changed = $false
          exit
        }
        Remove-Item -Path $source
      }
      mkdir.exe -p $env:AppData\lazygit
      New-Item -ItemType $type -Path "$source" -Target "$target"

- name: Install fd
  win_chocolatey:
    name: fd
    state: present

- name: Install lf
  win_chocolatey:
    name: lf
    state: present

- name: Install docker
  win_chocolatey:
    name: docker-desktop
    state: present

# dotnet SDKs
- name: Install dotnet 3.1 SDK
  win_chocolatey:
    name: dotnetcore-sdk
    state: present

- name: Install dotnet 5 SDK
  win_chocolatey:
    name: dotnet-5.0-sdk
    state: present

- name: Install dotnet 6 SDK
  win_chocolatey:
    name: dotnet-6.0-sdk
    state: present

- name: Install dotnet 7 SDK
  win_chocolatey:
    name: dotnet-7.0-sdk
    state: present

- name: Install dotpeek
  win_chocolatey:
    name: dotpeek
    state: present

- name: Install SSMS
  win_chocolatey:
    name: sql-server-management-studio
    state: present

- name: Install SQL Server 2019 Express
  ansible.windows.win_powershell:
    script: |
      winget install Microsoft.SQLServer.2019.Express

# TODO: Add SQLBK to env var

- name: Install TablePlus
  win_chocolatey:
    name: tableplus
    state: present

# TODO: Configure above apps
# TODO: Generate an SSH Key
# TODO: Setup WSL
# TODO: Setup Tmux