---
# Install extra applications that are nice to have

- name: Install OBS Studio
  win_chocolatey:
    name: obs-studio
    state: present

- name: Install LibreOffice
  win_chocolatey:
    name: libreoffice-fresh
    state: present

- name: Install Wireguard
  win_chocolatey:
    name: wireguard
    state: present

- name: Install Obsidian
  win_chocolatey:
    name: obsidian
    state: present

# - name: Install Spotify
#   win_chocolatey:
#     name: spotify
#     state: present

- name: Install WinDirStat
  win_chocolatey:
    name: windirstat
    state: present

- name: Install ScreenToGif
  win_chocolatey:
    name: screentogif
    state: present

- name: Install Lightshot
  win_chocolatey:
    name: lightshot
    state: present

- name: Install VLC
  win_chocolatey:
    name: vlc
    state: present

- name: Install ffmpeg
  win_chocolatey:
    name: ffmpeg
    state: present

- name: Install ZoomIt
  win_chocolatey:
    name: zoomit
    state: present

- name: Install FancyWM
  ansible.windows.win_powershell:
    script: |
      winget install 9P1741LKHQS9

- name: Configure FancyWM
  ansible.windows.win_powershell:
    script: |
      $source = "$env:LocalAppData\Packages\2203VeselinKaraganev.FancyWM_9x2ndwrcmyd2c\LocalCache\Roaming\FancyWM\settings.json"
      $target = "{{ dotfiles_repo_fullpath }}\win\config\FancyWM\settings.json"
      $type = "HardLink"
      $existing = Get-Item -Path $source -ErrorAction SilentlyContinue
      if ($?) {
        if ($existing.LinkType -eq $type)
        {
          $Ansible.Changed = $false
          exit
        }
        Remove-Item -Path $source
      }
      New-Item -ItemType $type -Path "$source" -Target "$target"

- name: Install RegionToShare
  ansible.windows.win_powershell:
    script: |
      winget install 9N4066W2R5Q4
